/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.NiryoOne
{
    public class ToolCommand : Message
    {
        public const string RosMessageName = "niryo_one_msgs/ToolCommand";

        public byte tool_id { get; set; }
        public byte cmd_type { get; set; }
        //  if gripper close
        public ushort gripper_close_speed { get; set; }
        //  if gripper open
        public ushort gripper_open_speed { get; set; }
        //  if vacuum pump or electromagnet grove
        public bool activate { get; set; }
        //  if tool is set by digital outputs (electromagnet)
        public byte gpio { get; set; }

        public ToolCommand()
        {
            this.tool_id = 0;
            this.cmd_type = 0;
            this.gripper_close_speed = 0;
            this.gripper_open_speed = 0;
            this.activate = false;
            this.gpio = 0;
        }

        public ToolCommand(byte tool_id, byte cmd_type, ushort gripper_close_speed, ushort gripper_open_speed, bool activate, byte gpio)
        {
            this.tool_id = tool_id;
            this.cmd_type = cmd_type;
            this.gripper_close_speed = gripper_close_speed;
            this.gripper_open_speed = gripper_open_speed;
            this.activate = activate;
            this.gpio = gpio;
        }
    }
}
